package com.resilientgeo.mesh.trust

import org.json.JSONObject
import java.time.Instant

/**
 * `fixtures/crowd-reports-v0.json` (byte-identical copy under test resources),
 * generated by `pipeline/tools/generate-crowd-fixture.mjs`. The device and
 * official keys come from fixed seeds so Kotlin can recreate them here.
 */
object CrowdFixtures {
    val root: JSONObject by lazy {
        val text = checkNotNull(CrowdFixtures::class.java.classLoader?.getResourceAsStream("fixtures/crowd-reports-v0.json")) {
            "missing test resource: fixtures/crowd-reports-v0.json"
        }.bufferedReader().use { it.readText() }
        JSONObject(text)
    }

    val now: Instant get() = Instant.parse(root.getString("now"))

    fun trustStore(): TrustedKeyStore =
        TrustedKeyStore(mapOf(root.getString("official_key_id") to root.getString("official_public_key")))

    fun eventCase(name: String): JSONObject = namedCase("event_cases", name)

    fun chunkCase(name: String): JSONObject = namedCase("chunk_cases", name)

    fun eventCases(): List<JSONObject> = cases("event_cases")

    fun chunkCases(): List<JSONObject> = cases("chunk_cases")

    fun attestations(): List<JSONObject> {
        val list = root.getJSONArray("attestations")
        return (0 until list.length()).map { copy(list.getJSONObject(it)) }
    }

    /** Same seed derivation as keyPairFromSeed() in the generator: UTF-8 label, zero padded to 32 bytes. */
    fun deviceKey(label: String): DeviceSigningKey {
        val seed = ByteArray(32)
        label.toByteArray(Charsets.UTF_8).copyInto(seed)
        return DeviceSigningKey.fromSeed(seed)
    }

    /** A fresh copy each call, so tests can mutate it. */
    fun copy(json: JSONObject): JSONObject = JSONObject(json.toString())

    private fun cases(key: String): List<JSONObject> {
        val list = root.getJSONArray(key)
        return (0 until list.length()).map { copy(list.getJSONObject(it)) }
    }

    /** Copies, so a test that mutates a case cannot leak into the next one. */
    private fun namedCase(key: String, name: String): JSONObject =
        cases(key).firstOrNull { it.getString("name") == name } ?: error("no $key case named $name")
}
