package com.resilientgeo.mesh.data

import android.content.Context
import com.resilientgeo.mesh.ingest.EventIngestor
import com.resilientgeo.mesh.ingest.IngestResult
import com.resilientgeo.mesh.protocol.ChunkVerifier
import com.resilientgeo.mesh.trust.TrustedKeyStore
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.time.Instant
import java.time.format.DateTimeFormatter
import java.time.temporal.ChronoUnit

/**
 * Wires the trust adapter and apply rules to Room. This is the only class
 * that knows both "how to verify an event" and "where events are stored" —
 * everything else talks to [com.resilientgeo.mesh.ingest.EventStore] or a
 * plain [org.json.JSONObject].
 */
class MeshRepository(context: Context) {
    private val appContext = context.applicationContext
    private val db = AppDatabase.get(appContext)
    private val store = RoomEventStore(db.eventDao())
    private val chunkDao = db.chunkDao()

    /**
     * Raw bytes of every verified chunk this node holds, keyed by
     * (datasetId, namespace, chunkId) — separate from [ChunkEntity], which
     * deliberately only records metadata (see its doc comment). Automatic
     * relaying needs both: a node must be able to describe what it has
     * (ChunkEntity) *and* actually hand the bytes to the next peer that asks
     * (this cache) — without it, a relay can advertise a chunk in HELLO but
     * has nothing to send when REQUESTed for it.
     */
    private val chunkCacheDir: File by lazy {
        File(appContext.filesDir, "chunk-cache").apply { mkdirs() }
    }

    private val trustStore: TrustedKeyStore by lazy {
        val json = appContext.assets.open(TRUSTED_KEYS_ASSET).bufferedReader().use { it.readText() }
        TrustedKeyStore.fromJson(json)
    }

    fun observeEvents(): Flow<List<EventEntity>> = db.eventDao().observeAll()

    /**
     * Ingests the bundled test-area event batch (real Ed25519 signatures,
     * generated by `scratch-generate-android-fixture.mjs` from the same
     * `pipeline/lib` module A owns) as if it had just arrived over the
     * network. In phase 1 this is the only data source; phase 3 will feed
     * this same path from Peer Sync instead.
     */
    suspend fun ingestBundledFixture(): List<IngestResult> = withContext(Dispatchers.IO) {
        val json = appContext.assets.open(FIXTURE_ASSET).bufferedReader().use { it.readText() }
        val events = JSONObject(json).getJSONArray("events")
        val now = Instant.now()
        (0 until events.length()).map { index ->
            EventIngestor.ingest(store, events.getJSONObject(index), trustStore, now)
        }
    }

    /**
     * TRANSFER entry point for Peer Sync (docs/jia-task-sequence.md item 7,
     * the "3a milestone"): verifies a `chunk-v0` payload received over
     * `BleGattTransport` — chunk_hash + chunk-level Ed25519 signature via
     * [ChunkVerifier], then each individual event via the same
     * [EventIngestor] path [ingestBundledFixture] already uses — and only
     * then writes to Room. A chunk that fails verification never reaches
     * [EventIngestor]/Room at all.
     */
    suspend fun ingestChunk(chunk: JSONObject): ChunkIngestResult = withContext(Dispatchers.IO) {
        when (val verified = ChunkVerifier.verify(chunk, trustStore)) {
            is ChunkVerifier.Result.Invalid -> ChunkIngestResult.Rejected(verified.reason)
            is ChunkVerifier.Result.Valid -> {
                val now = Instant.now()
                val results = verified.events.map { event -> EventIngestor.ingest(store, event, trustStore, now) }
                // Record the chunk itself, not just its events, so this node
                // can later describe its own inventory in HELLO. Written only
                // after verification passes, so the inventory can never
                // advertise a chunk that failed the trust check.
                chunkDao.upsertSync(chunk.toChunkEntity(now))
                cacheChunkBytes(chunk)
                ChunkIngestResult.Applied(results)
            }
        }
    }

    /**
     * Build this node's `peer-summary-v0` HELLO payload from what is
     * actually in Room, rather than from a hand-written fixture.
     *
     * This is what makes the mesh able to sustain itself: a node that
     * received a chunk can now tell the *next* peer it has it, so a third
     * device can pull from a relay instead of only from the original
     * source. `dataset_version` / `manifest_id` are taken from the newest
     * chunk held for the dataset, matching the DTN supersession rule in
     * `PeerSync.computeDiff` (a node advertises the newest manifest it has
     * actually seen).
     *
     * Returns a summary with an empty chunk list when this node holds
     * nothing for the dataset — that is a legitimate HELLO ("I have
     * nothing, send me everything"), not an error.
     */
    suspend fun localPeerSummary(
        nodeId: String,
        datasetId: String,
        namespace: String,
        fallbackManifestId: String,
        fallbackDatasetVersion: Int,
    ): JSONObject = withContext(Dispatchers.IO) {
        val dataset = buildDatasetJson(datasetId, namespace, fallbackManifestId, fallbackDatasetVersion)
        peerSummaryEnvelope(nodeId, JSONArray().put(dataset))
    }

    /**
     * Same HELLO shape as [localPeerSummary], but covering every dataset this
     * node actually holds anything for, rather than one hardcoded pair.
     *
     * This is what makes automatic sync (`AutoPeerSyncEngine`) able to relay
     * more than the single demo dataset: [localPeerSummary] was built for the
     * two-device Peer Sync milestone, where the dataset/namespace pair to
     * describe was chosen on screen by a human. Automatic sync has no such
     * moment and no advance knowledge of what a stranger might be carrying,
     * so it needs a HELLO that enumerates this node's *entire* inventory —
     * plus [KNOWN_DATASETS], so a brand-new node with zero chunks still
     * advertises "I have nothing for this dataset" rather than omitting it
     * (an omitted dataset and "I have zero chunks of it" are not the same
     * claim: only the latter tells a peer there is something to send).
     */
    suspend fun allLocalPeerSummaries(nodeId: String): JSONObject = withContext(Dispatchers.IO) {
        val heldPairs = chunkDao.allSync().map { it.datasetId to it.namespace }.distinct()
        val seen = mutableSetOf<Pair<String, String>>()
        val datasets = JSONArray()

        for (known in KNOWN_DATASETS) {
            datasets.put(buildDatasetJson(known.datasetId, known.namespace, known.fallbackManifestId, known.fallbackDatasetVersion))
            seen += known.datasetId to known.namespace
        }
        for ((datasetId, namespace) in heldPairs) {
            if (!seen.add(datasetId to namespace)) continue
            // No fallback needed here: `held` for a pair reached only via
            // heldPairs is guaranteed non-empty, so buildDatasetJson always
            // finds a `newest` chunk and never falls back.
            datasets.put(buildDatasetJson(datasetId, namespace, fallbackManifestId = "unknown", fallbackDatasetVersion = 0))
        }

        peerSummaryEnvelope(nodeId, datasets)
    }

    private fun buildDatasetJson(
        datasetId: String,
        namespace: String,
        fallbackManifestId: String,
        fallbackDatasetVersion: Int,
    ): JSONObject {
        val held = chunkDao.forDatasetSync(datasetId, namespace)
        val newest = held.maxByOrNull { it.datasetVersion }

        val chunks = JSONArray()
        held.filter { newest == null || it.datasetVersion == newest.datasetVersion }
            .forEach { entity ->
                chunks.put(
                    JSONObject()
                        .put("chunk_id", entity.chunkId)
                        .put("chunk_hash", entity.chunkHash)
                        .put("size_bytes", entity.sizeBytes)
                        .put("priority", entity.priority)
                        .put("state", "available"),
                )
            }

        return JSONObject()
            .put("dataset_id", datasetId)
            .put("namespace", namespace)
            .put("manifest_id", newest?.manifestId ?: fallbackManifestId)
            .put("dataset_version", newest?.datasetVersion ?: fallbackDatasetVersion)
            .put("chunks", chunks)
    }

    // Every field `schemas/peer-summary-v0.schema.json` marks required. The
    // hand-written summaries this replaced carried only
    // schema_version/node_id/datasets, so the HELLO actually going over the
    // air did not conform to the schema the project publishes as its module
    // interface — and nothing noticed, because the parser only reads
    // node_id and datasets.
    private fun peerSummaryEnvelope(nodeId: String, datasets: JSONArray): JSONObject {
        val now = Instant.now()
        return JSONObject()
            .put("schema_version", "peer-summary-v0")
            .put("protocol_version", "0")
            .put("node_id", nodeId)
            .put("generated_at", DateTimeFormatter.ISO_INSTANT.format(now.truncatedTo(ChronoUnit.SECONDS)))
            .put("capabilities", capabilities())
            .put("datasets", datasets)
    }

    /**
     * Bytes of a chunk this node has already verified and cached, for
     * serving a peer's REQUEST. Returns null both when this node never held
     * the chunk and when it aged out of [CHUNK_CACHE_CAP_BYTES] — either way
     * the caller's correct response is "I don't have it", never a crash.
     */
    suspend fun cachedChunkJson(datasetId: String, namespace: String, chunkId: String): JSONObject? =
        withContext(Dispatchers.IO) {
            val file = chunkCacheFile(datasetId, namespace, chunkId)
            if (!file.isFile) null else JSONObject(file.readText())
        }

    private fun cacheChunkBytes(chunk: JSONObject) {
        val file = chunkCacheFile(
            datasetId = chunk.getString("dataset_id"),
            namespace = chunk.getString("namespace"),
            chunkId = chunk.getString("chunk_id"),
        )
        file.writeText(chunk.toString())
        evictChunkCacheIfOverCap()
    }

    private fun chunkCacheFile(datasetId: String, namespace: String, chunkId: String): File =
        File(chunkCacheDir, safeCacheFileName(datasetId, namespace, chunkId))

    /** chunk_id values contain ':' (e.g. "resilientgeo-demo:chunk:136:dahu:shelter:000"), not filesystem-safe on every target. */
    private fun safeCacheFileName(datasetId: String, namespace: String, chunkId: String): String =
        listOf(datasetId, namespace, chunkId).joinToString(separator = "__") { part ->
            part.map { c -> if (c.isLetterOrDigit() || c == '-' || c == '.') c else '_' }.joinToString("")
        } + ".json"

    /**
     * Oldest-first eviction once the cache exceeds [CHUNK_CACHE_CAP_BYTES].
     * The Neihu-scale dataset ADR-001 measured tops out around 46.6 KB for
     * its single largest chunk with 183 chunks total — comfortably under this
     * cap, so it is headroom rather than a real constraint at v0 scale, kept
     * as an explicit number so it doesn't grow unbounded at a larger scale.
     */
    private fun evictChunkCacheIfOverCap() {
        val files = chunkCacheDir.listFiles()?.sortedBy { it.lastModified() } ?: return
        var total = files.sumOf { it.length() }
        var index = 0
        while (total > CHUNK_CACHE_CAP_BYTES && index < files.size) {
            total -= files[index].length()
            files[index].delete()
            index++
        }
    }

    /**
     * What this node can actually do, per ADR-001: BLE for discovery and BLE
     * GATT for transfer, with byte-level resume proven on real devices. The
     * two Wi-Fi-based transports the schema also allows were rejected and
     * their implementations removed, so advertising them would be a lie a
     * peer could act on.
     */
    private fun capabilities(): JSONObject = JSONObject()
        .put("discovery_transports", JSONArray().put("BLE"))
        .put("transfer_transports", JSONArray().put("BLE_GATT"))
        .put("max_peer_count", MAX_PEER_COUNT)
        .put("supports_resume", true)
        .put("max_chunk_bytes", MAX_CHUNK_BYTES)

    /** How many verified chunks this node currently holds — for status UI/logs. */
    suspend fun heldChunkCount(): Int = withContext(Dispatchers.IO) { chunkDao.countSync() }

    private fun JSONObject.toChunkEntity(now: Instant) = ChunkEntity(
        datasetId = getString("dataset_id"),
        namespace = getString("namespace"),
        chunkId = getString("chunk_id"),
        manifestId = getString("manifest_id"),
        datasetVersion = getInt("dataset_version"),
        chunkHash = getString("chunk_hash"),
        // byte_length is the signed, authoritative size; falling back to the
        // serialized length would let two nodes disagree on size_bytes for
        // the same chunk and see a phantom diff.
        sizeBytes = optLong("byte_length", toString().toByteArray(Charsets.UTF_8).size.toLong()),
        priority = getString("priority"),
        receivedAtEpochMillis = now.toEpochMilli(),
    )

    companion object {
        /** Schema caps this at 5; ADR-001's contact windows make 4 the practical limit. */
        private const val MAX_PEER_COUNT = 4

        /**
         * Largest chunk this node will accept. The Neihu scale dataset's
         * biggest chunk is 46.6 KB (ADR-001), so 1 MiB is headroom rather
         * than a real constraint — it exists to bound what a peer can ask
         * this node to buffer.
         */
        private const val MAX_CHUNK_BYTES = 1048576

        /** Total on-disk size [evictChunkCacheIfOverCap] will keep the chunk-bytes cache under. */
        private const val CHUNK_CACHE_CAP_BYTES = 8L * 1024 * 1024

        /**
         * Datasets [allLocalPeerSummaries] always declares even with zero
         * chunks held, so a fresh node's HELLO says "I have nothing for
         * this" instead of omitting it — matching the identity the Peer
         * Sync milestone demo hardcoded (`PeerSyncMilestoneActivity`).
         */
        private val KNOWN_DATASETS = listOf(
            KnownDataset(
                datasetId = "resilientgeo-demo",
                namespace = "official",
                fallbackManifestId = "resilientgeo-demo:manifest:136",
                fallbackDatasetVersion = 136,
            ),
        )

        private const val FIXTURE_ASSET = "fixtures/signed-events.json"
        private const val TRUSTED_KEYS_ASSET = "trust/trusted-keys.json"
    }
}

private data class KnownDataset(
    val datasetId: String,
    val namespace: String,
    val fallbackManifestId: String,
    val fallbackDatasetVersion: Int,
)

sealed class ChunkIngestResult {
    data class Applied(val eventResults: List<IngestResult>) : ChunkIngestResult()
    data class Rejected(val reason: String) : ChunkIngestResult()
}
