package com.resilientgeo.mesh.data

import android.content.Context
import com.resilientgeo.mesh.ingest.EventIngestor
import com.resilientgeo.mesh.ingest.IngestResult
import com.resilientgeo.mesh.protocol.ChunkVerifier
import com.resilientgeo.mesh.trust.TrustedKeyStore
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.time.Instant

/**
 * Wires the trust adapter and apply rules to Room. This is the only class
 * that knows both "how to verify an event" and "where events are stored" —
 * everything else talks to [com.resilientgeo.mesh.ingest.EventStore] or a
 * plain [org.json.JSONObject].
 */
class MeshRepository(context: Context) {
    private val appContext = context.applicationContext
    private val db = AppDatabase.get(appContext)
    private val store = RoomEventStore(db.eventDao())
    private val chunkDao = db.chunkDao()

    private val trustStore: TrustedKeyStore by lazy {
        val json = appContext.assets.open(TRUSTED_KEYS_ASSET).bufferedReader().use { it.readText() }
        TrustedKeyStore.fromJson(json)
    }

    fun observeEvents(): Flow<List<EventEntity>> = db.eventDao().observeAll()

    /**
     * Ingests the bundled test-area event batch (real Ed25519 signatures,
     * generated by `scratch-generate-android-fixture.mjs` from the same
     * `pipeline/lib` module A owns) as if it had just arrived over the
     * network. In phase 1 this is the only data source; phase 3 will feed
     * this same path from Peer Sync instead.
     */
    suspend fun ingestBundledFixture(): List<IngestResult> = withContext(Dispatchers.IO) {
        val json = appContext.assets.open(FIXTURE_ASSET).bufferedReader().use { it.readText() }
        val events = JSONObject(json).getJSONArray("events")
        val now = Instant.now()
        (0 until events.length()).map { index ->
            EventIngestor.ingest(store, events.getJSONObject(index), trustStore, now)
        }
    }

    /**
     * TRANSFER entry point for Peer Sync (docs/jia-task-sequence.md item 7,
     * the "3a milestone"): verifies a `chunk-v0` payload received over
     * `BleGattTransport` — chunk_hash + chunk-level Ed25519 signature via
     * [ChunkVerifier], then each individual event via the same
     * [EventIngestor] path [ingestBundledFixture] already uses — and only
     * then writes to Room. A chunk that fails verification never reaches
     * [EventIngestor]/Room at all.
     */
    suspend fun ingestChunk(chunk: JSONObject): ChunkIngestResult = withContext(Dispatchers.IO) {
        when (val verified = ChunkVerifier.verify(chunk, trustStore)) {
            is ChunkVerifier.Result.Invalid -> ChunkIngestResult.Rejected(verified.reason)
            is ChunkVerifier.Result.Valid -> {
                val now = Instant.now()
                val results = verified.events.map { event -> EventIngestor.ingest(store, event, trustStore, now) }
                // Record the chunk itself, not just its events, so this node
                // can later describe its own inventory in HELLO. Written only
                // after verification passes, so the inventory can never
                // advertise a chunk that failed the trust check.
                chunkDao.upsertSync(chunk.toChunkEntity(now))
                ChunkIngestResult.Applied(results)
            }
        }
    }

    /**
     * Build this node's `peer-summary-v0` HELLO payload from what is
     * actually in Room, rather than from a hand-written fixture.
     *
     * This is what makes the mesh able to sustain itself: a node that
     * received a chunk can now tell the *next* peer it has it, so a third
     * device can pull from a relay instead of only from the original
     * source. `dataset_version` / `manifest_id` are taken from the newest
     * chunk held for the dataset, matching the DTN supersession rule in
     * `PeerSync.computeDiff` (a node advertises the newest manifest it has
     * actually seen).
     *
     * Returns a summary with an empty chunk list when this node holds
     * nothing for the dataset — that is a legitimate HELLO ("I have
     * nothing, send me everything"), not an error.
     */
    suspend fun localPeerSummary(
        nodeId: String,
        datasetId: String,
        namespace: String,
        fallbackManifestId: String,
        fallbackDatasetVersion: Int,
    ): JSONObject = withContext(Dispatchers.IO) {
        val held = chunkDao.forDatasetSync(datasetId, namespace)
        val newest = held.maxByOrNull { it.datasetVersion }

        val chunks = JSONArray()
        held.filter { newest == null || it.datasetVersion == newest.datasetVersion }
            .forEach { entity ->
                chunks.put(
                    JSONObject()
                        .put("chunk_id", entity.chunkId)
                        .put("chunk_hash", entity.chunkHash)
                        .put("size_bytes", entity.sizeBytes)
                        .put("priority", entity.priority)
                        .put("state", "available"),
                )
            }

        val dataset = JSONObject()
            .put("dataset_id", datasetId)
            .put("namespace", namespace)
            .put("manifest_id", newest?.manifestId ?: fallbackManifestId)
            .put("dataset_version", newest?.datasetVersion ?: fallbackDatasetVersion)
            .put("chunks", chunks)

        JSONObject()
            .put("schema_version", "peer-summary-v0")
            .put("node_id", nodeId)
            .put("datasets", JSONArray().put(dataset))
    }

    /** How many verified chunks this node currently holds — for status UI/logs. */
    suspend fun heldChunkCount(): Int = withContext(Dispatchers.IO) { chunkDao.countSync() }

    private fun JSONObject.toChunkEntity(now: Instant) = ChunkEntity(
        datasetId = getString("dataset_id"),
        namespace = getString("namespace"),
        chunkId = getString("chunk_id"),
        manifestId = getString("manifest_id"),
        datasetVersion = getInt("dataset_version"),
        chunkHash = getString("chunk_hash"),
        // byte_length is the signed, authoritative size; falling back to the
        // serialized length would let two nodes disagree on size_bytes for
        // the same chunk and see a phantom diff.
        sizeBytes = optLong("byte_length", toString().toByteArray(Charsets.UTF_8).size.toLong()),
        priority = getString("priority"),
        receivedAtEpochMillis = now.toEpochMilli(),
    )

    companion object {
        private const val FIXTURE_ASSET = "fixtures/signed-events.json"
        private const val TRUSTED_KEYS_ASSET = "trust/trusted-keys.json"
    }
}

sealed class ChunkIngestResult {
    data class Applied(val eventResults: List<IngestResult>) : ChunkIngestResult()
    data class Rejected(val reason: String) : ChunkIngestResult()
}
