package com.resilientgeo.mesh.transport

import android.Manifest
import android.bluetooth.BluetoothManager
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.util.Log
import android.widget.Button
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.activity.ComponentActivity
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.content.ContextCompat
import androidx.lifecycle.lifecycleScope
import com.resilientgeo.mesh.data.ChunkIngestResult
import com.resilientgeo.mesh.data.MeshRepository
import com.resilientgeo.mesh.protocol.PeerSummary
import com.resilientgeo.mesh.protocol.PeerSync
import com.resilientgeo.mesh.protocol.PeerSyncException
import com.resilientgeo.mesh.protocol.RequestMessage
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.nio.charset.StandardCharsets

/**
 * docs/jia-task-sequence.md item 7, the "3a milestone": two real devices
 * run HELLO -> DIFF -> REQUEST -> TRANSFER -> VERIFY/APPLY
 * (docs/peer-sync-v0.md) over [BleGattTransport], using [PeerSync] (乙's
 * Kotlin port of pipeline/lib/peer-sync.mjs) for the DIFF/REQUEST logic and
 * [MeshRepository.ingestChunk] (chunk_hash + chunk-level Ed25519 signature,
 * then each event through the same path `ingestBundledFixture` already
 * uses) for VERIFY/APPLY into Room.
 *
 * Both PeerSummary values below are hardcoded rather than computed from
 * Room — building a real inventory-to-PeerSummary path is Stage 3
 * scheduler territory (system.md §6), out of scope for proving the
 * protocol pipeline itself works end to end on real hardware. Node A
 * declares it has nothing for this dataset; Node B declares it holds
 * exactly the one real signed chunk generated by
 * `pipeline/tools/generate-peer-sync-chunk-fixture.mjs`
 * (assets/fixtures/peer-sync/chunk-136-dahu-shelter-000.json) — so
 * computeDiff() always finds that one chunk missing on A.
 *
 * Both devices run the identical APK; which hardcoded summary/behavior
 * applies is chosen at runtime by tapping "Node A" or "Node B" on each
 * physical device, not by what's bundled in assets (both have the chunk
 * asset installed either way, only the Node B code path ever reads it).
 */
class PeerSyncMilestoneActivity : ComponentActivity() {

    companion object {
        private const val TAG = "ResilientGeoPeerSync"
        private const val DATASET_ID = "resilientgeo-demo"
        private const val NAMESPACE = "official"
        private const val SERVED_CHUNK_ID = "resilientgeo-demo:chunk:136:dahu:shelter:000"
        private const val CHUNK_ASSET_PATH = "fixtures/peer-sync/chunk-136-dahu-shelter-000.json"

        private val NODE_A_SUMMARY = JSONObject(
            """
            {
              "schema_version": "peer-summary-v0",
              "node_id": "node-a",
              "datasets": [
                {
                  "dataset_id": "$DATASET_ID",
                  "namespace": "$NAMESPACE",
                  "manifest_id": "resilientgeo-demo:manifest:136",
                  "dataset_version": 136,
                  "chunks": []
                }
              ]
            }
            """.trimIndent(),
        )

        // chunk_hash/size_bytes must match the asset's real values exactly —
        // computeDiff() only compares these fields, never chunk content.
        private val NODE_B_SUMMARY = JSONObject(
            """
            {
              "schema_version": "peer-summary-v0",
              "node_id": "node-b",
              "datasets": [
                {
                  "dataset_id": "$DATASET_ID",
                  "namespace": "$NAMESPACE",
                  "manifest_id": "resilientgeo-demo:manifest:136",
                  "dataset_version": 136,
                  "chunks": [
                    {
                      "chunk_id": "$SERVED_CHUNK_ID",
                      "chunk_hash": "sha256:8b7b851074230f562de1d849753269b92ab87e2994eb56e812c43a463db5bb67",
                      "size_bytes": 1147,
                      "priority": "CRITICAL"
                    }
                  ]
                }
              ]
            }
            """.trimIndent(),
        )
    }

    private enum class Role { NODE_A, NODE_B }

    private lateinit var transport: BleGattTransport
    private lateinit var repository: MeshRepository
    private lateinit var statusText: TextView
    private lateinit var logText: TextView

    private var discoverJob: Job? = null
    private var receiveJob: Job? = null
    private var controlReceiveJob: Job? = null
    @Volatile private var discoveredPeerId: String? = null
    @Volatile private var role: Role? = null
    @Volatile private var connection: Connection? = null
    @Volatile private var remotePeerSummary: PeerSummary? = null

    /** Chunk ids Node B has already made one TRANSFER attempt for — the simulated
     *  mid-transfer interruption (see [serveChunk]) only fires on that first
     *  attempt, never on the resume that follows. */
    private val attemptedChunkIds = java.util.concurrent.ConcurrentHashMap.newKeySet<String>()

    private val requiredPermissions: Array<String>
        get() = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            arrayOf(
                Manifest.permission.BLUETOOTH_SCAN,
                Manifest.permission.BLUETOOTH_ADVERTISE,
                Manifest.permission.BLUETOOTH_CONNECT,
            )
        } else {
            arrayOf(Manifest.permission.ACCESS_FINE_LOCATION)
        }

    private val permissionLauncher = registerForActivityResult(
        ActivityResultContracts.RequestMultiplePermissions(),
    ) { results ->
        if (results.values.all { it }) {
            appendLog("permissions granted")
            startDiscovery()
        } else {
            appendLog("permissions denied: $results")
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val bluetoothManager = getSystemService(BluetoothManager::class.java)
        transport = BleGattTransport(applicationContext, bluetoothManager.adapter)
        repository = MeshRepository(applicationContext)

        setContentView(buildUi())

        receiveJob = lifecycleScope.launch {
            transport.receivedMessages.collect { (peerId, bytes) -> handleIncoming(peerId, bytes) }
        }
        controlReceiveJob = lifecycleScope.launch {
            transport.controlMessages.collect { (peerId, bytes) -> handleIncoming(peerId, bytes) }
        }

        val missing = requiredPermissions.filter {
            ContextCompat.checkSelfPermission(this, it) != PackageManager.PERMISSION_GRANTED
        }
        if (missing.isEmpty()) {
            startDiscovery()
        } else {
            permissionLauncher.launch(missing.toTypedArray())
        }
    }

    private fun buildUi(): LinearLayout {
        val padding = (16 * resources.displayMetrics.density).toInt()

        statusText = TextView(this).apply {
            text = "requesting permissions..."
            textSize = 16f
            setPadding(0, 0, 0, padding)
        }

        val roleButtons = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            addView(Button(this@PeerSyncMilestoneActivity).apply {
                text = "I am Node A (requester)"
                setOnClickListener { chooseRole(Role.NODE_A) }
            })
            addView(Button(this@PeerSyncMilestoneActivity).apply {
                text = "I am Node B (server)"
                setOnClickListener { chooseRole(Role.NODE_B) }
            })
        }

        logText = TextView(this).apply {
            text = ""
            textSize = 13f
            setTextIsSelectable(true)
        }
        val logScroll = ScrollView(this).apply { addView(logText) }

        return LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setPadding(padding, padding, padding, padding)
            addView(statusText)
            addView(roleButtons)
            addView(logScroll, LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, 0, 1f))
        }
    }

    private fun startDiscovery() {
        statusText.text = "advertising + scanning in background..."
        discoverJob?.cancel()
        discoverJob = lifecycleScope.launch {
            transport.discover().collect { advertisement ->
                if (discoveredPeerId == null) {
                    discoveredPeerId = advertisement.peerId
                    statusText.text = "peer discovered: ${advertisement.peerId}"
                    appendLog("peer discovered: ${advertisement.peerId}")
                }
            }
        }
    }

    private fun chooseRole(chosen: Role) {
        if (role != null) {
            appendLog("role already set to $role, ignoring tap")
            return
        }
        role = chosen
        statusText.text = "role=$chosen"
        appendLog("role set to $chosen")
        val peerId = discoveredPeerId ?: run { appendLog("no peer discovered yet — tap again once one shows up"); return }
        lifecycleScope.launch {
            try {
                val conn = transport.connect(peerId)
                connection = conn
                appendLog("connected to $peerId as $chosen")
                val summary = if (chosen == Role.NODE_A) NODE_A_SUMMARY else NODE_B_SUMMARY
                sendEnvelope(conn, JSONObject().put("type", "HELLO").put("summary", summary))
                appendLog("sent HELLO")
            } catch (e: Exception) {
                appendLog("connect/HELLO failed: ${e.message}")
            }
        }
    }

    private suspend fun sendEnvelope(conn: Connection, envelope: JSONObject) {
        val bytes = envelope.toString().toByteArray(StandardCharsets.UTF_8)
        when (val result = transport.send(conn, bytes)) {
            is TransferResult.Success -> {}
            else -> appendLog("send failed for envelope type=${envelope.optString("type")}: $result")
        }
    }

    private suspend fun handleIncoming(peerId: String, bytes: ByteArray) {
        val envelope = try {
            JSONObject(String(bytes, StandardCharsets.UTF_8))
        } catch (e: Exception) {
            appendLog("received non-JSON payload from $peerId (${bytes.size} bytes), ignoring")
            return
        }
        when (envelope.optString("type")) {
            "HELLO" -> handleHello(envelope.getJSONObject("summary"))
            "REQUEST" -> handleRequest(envelope.getJSONObject("request"))
            "TRANSFER" -> handleTransfer(envelope.getJSONObject("chunk"))
            "TRANSFER_INTERRUPTED" -> handleTransferInterrupted(envelope)
            else -> appendLog("unknown envelope type: ${envelope.optString("type")}")
        }
    }

    private suspend fun handleHello(remoteSummaryJson: JSONObject) {
        appendLog("received HELLO: node_id=${remoteSummaryJson.optString("node_id")}")
        if (role != Role.NODE_A) return

        val localSummary = PeerSummary.fromJson(NODE_A_SUMMARY)
        val remoteSummary = PeerSummary.fromJson(remoteSummaryJson)
        remotePeerSummary = remoteSummary
        val diff = try {
            PeerSync.computeDiff(localSummary, remoteSummary, DATASET_ID, NAMESPACE)
        } catch (e: PeerSyncException) {
            appendLog("computeDiff failed: ${e.message}")
            return
        }
        appendLog(
            "DIFF: missing=${diff.missingChunks.map { it.chunkId }} stale=${diff.staleChunks.map { it.chunkId }}",
        )
        if (diff.missingChunks.isEmpty() && diff.staleChunks.isEmpty()) {
            appendLog("nothing to request, already in sync")
            return
        }

        val request = PeerSync.buildRequest(diff)
        val conn = connection ?: run { appendLog("no connection to send REQUEST on"); return }
        sendEnvelope(conn, JSONObject().put("type", "REQUEST").put("request", requestToJson(request)))
        appendLog("sent REQUEST for ${request.chunks.map { it.chunkId }}, max_total_bytes=${request.maxTotalBytes}")
    }

    private suspend fun handleRequest(requestJson: JSONObject) {
        if (role != Role.NODE_B) return
        val conn = connection ?: run { appendLog("no connection to send TRANSFER on"); return }
        val chunksRequested = requestJson.getJSONArray("chunks")
        for (i in 0 until chunksRequested.length()) {
            val chunkReq = chunksRequested.getJSONObject(i)
            val chunkId = chunkReq.getString("chunk_id")
            val offsetBytes = chunkReq.optLong("offset_bytes", 0L)
            appendLog("received REQUEST for $chunkId offset_bytes=$offsetBytes")
            if (chunkId != SERVED_CHUNK_ID) {
                appendLog("don't have $chunkId, skipping")
                continue
            }
            serveChunk(chunkId, offsetBytes, conn)
        }
    }

    /**
     * docs/jia-task-sequence.md item 8, cross-contact resume. On the first
     * attempt (offsetBytes == 0), deliberately cuts the TRANSFER short after
     * ~1 GATT write — as if the opportunistic contact window closed
     * mid-transfer — then tells the peer exactly how far it got so the next
     * REQUEST can carry the right `offset_bytes` instead of starting over.
     *
     * This still holds the same GATT connection open throughout (only
     * [BleGattTransport.interruptRequested] pauses the sender), so it proves
     * REQUEST/TRANSFER now correctly plumbs `offset_bytes` through to
     * BleGattTransport's already-proven byte-level resume() — not that a
     * receiver can resume after an actual link drop. BleGattTransport's GATT
     * server currently discards a peripheral's in-progress receive buffer on
     * disconnect (`incomingMessages.remove(device.address)`), so surviving a
     * *real* disconnect would need the receiver to persist partial-chunk
     * state durably keyed by peer identity — a bigger change, out of scope
     * here.
     *
     * The resume itself needs no separate TRANSFER re-announcement: the
     * receiver's [BleGattTransport] reassembles a message purely from raw
     * byte count against the length header sent in the very first write, so
     * once resume() delivers the remaining bytes the same "TRANSFER"
     * envelope completes and fires exactly like an uninterrupted transfer —
     * [handleTransfer] runs unchanged either way.
     */
    private suspend fun serveChunk(chunkId: String, offsetBytes: Long, conn: Connection) {
        val chunkJson = withContext(Dispatchers.IO) {
            JSONObject(assets.open(CHUNK_ASSET_PATH).bufferedReader().use { it.readText() })
        }
        val envelopeBytes = JSONObject().put("type", "TRANSFER").put("chunk", chunkJson)
            .toString().toByteArray(StandardCharsets.UTF_8)

        if (offsetBytes == 0L && attemptedChunkIds.add(chunkId)) {
            val interruptJob = lifecycleScope.launch {
                delay(80)
                transport.interruptRequested = true
            }
            val result = transport.send(conn, envelopeBytes)
            interruptJob.cancel()
            transport.interruptRequested = false
            when (result) {
                is TransferResult.Interrupted -> {
                    appendLog(
                        "TRANSFER for $chunkId interrupted at ${result.bytesTransferred}/${envelopeBytes.size} " +
                            "bytes (simulated contact-window close)",
                    )
                    val notice = JSONObject().put("type", "TRANSFER_INTERRUPTED")
                        .put("chunk_id", chunkId)
                        .put("bytes_sent", result.bytesTransferred)
                        .toString().toByteArray(StandardCharsets.UTF_8)
                    // Deliberately NOT sendEnvelope()/transport.send(): that
                    // would share DATA_CHARACTERISTIC with the still-incomplete
                    // TRANSFER above — see CONTROL_CHARACTERISTIC_UUID's doc
                    // comment for why that silently wedges instead of erroring.
                    when (val controlResult = transport.sendControl(conn, notice)) {
                        is TransferResult.Success -> {}
                        else -> appendLog("failed to notify peer of interruption: $controlResult")
                    }
                }
                is TransferResult.Success ->
                    appendLog("sent TRANSFER for $chunkId whole (didn't land mid-write this run, nothing to resume)")
                is TransferResult.Failed -> appendLog("TRANSFER for $chunkId failed: ${result.reason}")
            }
        } else {
            appendLog("resuming TRANSFER for $chunkId from offset_bytes=$offsetBytes")
            when (val result = transport.resume(conn, envelopeBytes, offsetBytes)) {
                is TransferResult.Success ->
                    appendLog("RESUME_RESULT chunk_id=$chunkId outcome=ok bytes_sent_this_call=${result.bytesTransferred}")
                is TransferResult.Interrupted ->
                    appendLog("RESUME_RESULT chunk_id=$chunkId outcome=interrupted_again bytes=${result.bytesTransferred}")
                is TransferResult.Failed -> appendLog("RESUME_RESULT chunk_id=$chunkId outcome=failed reason=${result.reason}")
            }
        }
    }

    private suspend fun handleTransferInterrupted(json: JSONObject) {
        if (role != Role.NODE_A) return
        val chunkId = json.getString("chunk_id")
        val bytesSent = json.getLong("bytes_sent")
        appendLog("peer reports TRANSFER for $chunkId interrupted at $bytesSent bytes — sending resume REQUEST")

        val chunkSummary = remotePeerSummary?.datasets?.flatMap { it.chunks }?.find { it.chunkId == chunkId }
            ?: run { appendLog("no known chunk metadata for $chunkId (never got peer's HELLO?), can't resume"); return }
        val conn = connection ?: run { appendLog("no connection to resume on"); return }

        val resumeChunkJson = JSONObject()
            .put("chunk_id", chunkSummary.chunkId)
            .put("chunk_hash", chunkSummary.chunkHash)
            .put("priority", chunkSummary.priority.name)
            .put("offset_bytes", bytesSent)
            .put("max_bytes", chunkSummary.sizeBytes)
        val resumeRequestJson = JSONObject()
            .put("dataset_id", DATASET_ID)
            .put("namespace", NAMESPACE)
            .put("manifest_id", "resilientgeo-demo:manifest:136")
            .put("chunks", JSONArray().put(resumeChunkJson))
            .put("resume", true)
            .put("max_total_bytes", chunkSummary.sizeBytes - bytesSent)
        sendEnvelope(conn, JSONObject().put("type", "REQUEST").put("request", resumeRequestJson))
        appendLog("sent resume REQUEST for $chunkId offset_bytes=$bytesSent")
    }

    private suspend fun handleTransfer(chunkJson: JSONObject) {
        if (role != Role.NODE_A) return
        appendLog("received TRANSFER: chunk_id=${chunkJson.optString("chunk_id")}, verifying...")
        when (val result = repository.ingestChunk(chunkJson)) {
            is ChunkIngestResult.Rejected ->
                appendLog("PEER_SYNC_3A_RESULT outcome=rejected reason=${result.reason}")
            is ChunkIngestResult.Applied -> {
                result.eventResults.forEachIndexed { i, r -> appendLog("event[$i] ingest result: $r") }
                appendLog("PEER_SYNC_3A_RESULT outcome=applied event_count=${result.eventResults.size}")
            }
        }
    }

    private fun requestToJson(request: RequestMessage): JSONObject {
        val chunksArray = JSONArray()
        for (c in request.chunks) {
            chunksArray.put(
                JSONObject()
                    .put("chunk_id", c.chunkId)
                    .put("chunk_hash", c.chunkHash)
                    .put("priority", c.priority.name)
                    .put("offset_bytes", c.offsetBytes)
                    .put("max_bytes", c.maxBytes),
            )
        }
        return JSONObject()
            .put("dataset_id", request.datasetId)
            .put("namespace", request.namespace)
            .put("manifest_id", request.manifestId)
            .put("chunks", chunksArray)
            .put("resume", request.resume)
            .put("max_total_bytes", request.maxTotalBytes)
            .apply { request.supersededManifestId?.let { put("superseded_manifest_id", it) } }
    }

    private fun appendLog(line: String) {
        Log.i(TAG, line)
        runOnUiThread { logText.append("$line\n") }
    }

    override fun onDestroy() {
        discoverJob?.cancel()
        receiveJob?.cancel()
        controlReceiveJob?.cancel()
        transport.teardown()
        super.onDestroy()
    }
}
